server:
  port: 9000
spring:
  application:
    name: zuul

instance:
  instance-id: zuul-1
  prefer-ip-address: true
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka3000.com:3000/eureka,http://www.eureka3001.com:3001/eureka,http://www.eureka3002.com:3002/eureka
zuul:
  prefix: /api
  ignored-services: "*"
  routes:
    mypower:
      serviceId: userClient
      path: /user/**
    myorder:
      serviceId: order1
      path: /order/**
